// Package schemagen shows the struct-as-single-source-of-truth
// workflow: the struct below carries the schema in its tags, and
// models_drops_schema.go — generated by `dropsgen -schema` — holds
// the typed table and column handles derived from it.
//
// The two cannot drift. Every column exists because a field declared
// it, so pg.NewEntity's check that no column is left unbound is
// satisfied by construction rather than by discipline.
//
// schemagen_drops_rows.go — generated by `dropsgen -rows` — runs the
// same argument backwards, off the table declaration rather than off
// this struct: UsersRow is what a SELECT hands back, UsersInsert is
// what a caller supplies, and neither can pair a column that admits
// NULL with a field that cannot receive one. Round-tripped through
// both generators, the struct comes back the way it went in; the test
// file says so.
//
// schemagen_drops_rels.go — generated by `dropsgen -rels` — is the
// third shape, and the one nobody should be retyping: what an eager
// load hands back. UsersWithPosts is a user row with its posts
// attached, and every part of it that could be got wrong by hand —
// the field name, the slice, the dropRel tag, the nested type — is
// derived from the relation declaration in relations.go.
//
//go:generate go run github.com/bernardoforcillo/drops/cmd/dropsgen -schema models.go
package schemagen

import "time"

//drops:schema table=Users name=users
type User struct {
	ID        int64     `drop:"id,primaryKey,autoIncrement"`
	Email     string    `drop:"email,notNull,unique"`
	Name      string    `drop:"name,notNull"`
	Age       *int32    `drop:"age"`
	CreatedAt time.Time `drop:"createdAt,notNull,default=now()"`
}

// Post is the far side of a relation, which is what makes an
// eager-load shape worth generating at all.
//
// Its columns are spelled snake_case where User's are camelCase, on
// purpose: a schema uses one convention or the other and the
// generators follow whichever it is — "user_id" becomes UserID,
// "createdAt" becomes CreatedAt, and neither is a name anybody had to
// choose twice.
//
//drops:schema table=Posts name=posts
type Post struct {
	ID     int64  `drop:"id,primaryKey,autoIncrement"`
	UserID int64  `drop:"user_id,notNull"`
	Title  string `drop:"title,notNull"`
}
