// Code generated by dropsgen. DO NOT EDIT.
//
// The schema below is derived from the `drop` struct tags in the
// source file. Edit the struct, not this file: a change here is
// reverted the next time dropsgen runs, and a schema that disagrees
// with its struct is exactly the drift this generator removes.

package schemagen

import "github.com/bernardoforcillo/drops/pg"

// Users is the "users" table, derived from User.
var (
	Users         = pg.NewTable("users")
	UserID        = pg.Add(Users, pg.BigSerial("id").PrimaryKey())
	UserEmail     = pg.Add(Users, pg.Text("email").NotNull().Unique())
	UserName      = pg.Add(Users, pg.Text("name").NotNull())
	UserAge       = pg.Add(Users, pg.Integer("age"))
	UserCreatedAt = pg.Add(Users, pg.Timestamp("createdAt", true).NotNull().Default("now()"))
)
