// Package schemagen shows the struct-as-single-source-of-truth
// workflow: the struct below carries the schema in its tags, and
// models_drops_schema.go — generated by `dropsgen -schema` — holds
// the typed table and column handles derived from it.
//
// The two cannot drift. Every column exists because a field declared
// it, so pg.NewEntity's check that no column is left unbound is
// satisfied by construction rather than by discipline.
//
// schemagen_drops_rows.go — generated by `dropsgen -rows` — runs the
// same argument backwards, off the table declaration rather than off
// this struct: UsersRow is what a SELECT hands back, UsersInsert is
// what a caller supplies, and neither can pair a column that admits
// NULL with a field that cannot receive one. Round-tripped through
// both generators, the struct comes back the way it went in; the test
// file says so.
//
//go:generate go run github.com/bernardoforcillo/drops/cmd/dropsgen -schema models.go
package schemagen

import "time"

//drops:schema table=Users name=users
type User struct {
	ID        int64     `drop:"id,primaryKey,autoIncrement"`
	Email     string    `drop:"email,notNull,unique"`
	Name      string    `drop:"name,notNull"`
	Age       *int32    `drop:"age"`
	CreatedAt time.Time `drop:"createdAt,notNull,default=now()"`
}
