// Package schemagen shows the struct-as-single-source-of-truth
// workflow: the struct below carries the schema in its tags, and
// models_drops_schema.go — generated by `dropsgen -schema` — holds
// the typed table and column handles derived from it.
//
// The two cannot drift. Every column exists because a field declared
// it, so pg.NewEntity's check that no column is left unbound is
// satisfied by construction rather than by discipline.
//
// schemagen_drops_rows.go — generated by `dropsgen -rows` — runs the
// same argument backwards, off the table declaration rather than off
// this struct: UsersRow is what a SELECT hands back, UsersInsert is
// what a caller supplies, and neither can pair a column that admits
// NULL with a field that cannot receive one. Round-tripped through
// both generators, the struct comes back the way it went in; the test
// file says so.
//
// schemagen_drops_rels.go — generated by `dropsgen -rels` — is the
// third shape, and the one nobody should be retyping: what an eager
// load hands back. UsersWithPosts is a user row with its posts
// attached, and every part of it that could be got wrong by hand —
// the field name, the slice, the dropRel tag, the nested type — is
// derived from the relation declaration in relations.go.
//
// The tables below declare more than a reader needs to follow the
// workflow, and that is deliberate: the field type is the decision
// -rels makes, it makes a different one for each of the six relation
// kinds, and a kind no generated struct covers is a decision only a
// hand-written mirror ever checks. So there is a profile for the
// HasOne, a junction for the ManyToMany, and a notes table that is
// both halves of the polymorphic pair.
//
//go:generate go run github.com/bernardoforcillo/drops/cmd/dropsgen -schema models.go
package schemagen

import "time"

//drops:schema table=Users name=users
type User struct {
	ID        int64     `drop:"id,primaryKey,autoIncrement"`
	Email     string    `drop:"email,notNull,unique"`
	Name      string    `drop:"name,notNull"`
	Age       *int32    `drop:"age"`
	CreatedAt time.Time `drop:"createdAt,notNull,default=now()"`
}

// Post is the far side of a relation, which is what makes an
// eager-load shape worth generating at all.
//
// Its columns are spelled snake_case where User's are camelCase, on
// purpose: a schema uses one convention or the other and the
// generators follow whichever it is — "user_id" becomes UserID,
// "createdAt" becomes CreatedAt, and neither is a name anybody had to
// choose twice.
//
//drops:schema table=Posts name=posts
type Post struct {
	ID     int64  `drop:"id,primaryKey,autoIncrement"`
	UserID int64  `drop:"user_id,notNull"`
	Title  string `drop:"title,notNull"`
}

// Profile is the HasOne side. A user has at most one, and "at most"
// is the whole difficulty: the row is either there or it is not, and
// the generated field is a pointer because those are two states a
// value struct only has one spelling for.
//
//drops:schema table=Profiles name=profiles
type Profile struct {
	ID     int64  `drop:"id,primaryKey,autoIncrement"`
	UserID int64  `drop:"user_id,notNull"`
	Bio    string `drop:"bio,notNull"`
}

// Tag is the far side of the ManyToMany, and PostTag is the junction
// that joins it. The junction is a table like any other — it has to
// be, because the loader queries it — but no shape ever nests its row
// struct: a ManyToMany field holds the target's rows, and the
// junction is the thing the reader never sees.
//
//drops:schema table=Tags name=tags
type Tag struct {
	ID    int64  `drop:"id,primaryKey,autoIncrement"`
	Label string `drop:"label,notNull"`
}

// PostTag has no key of its own, which is what a junction usually
// looks like: the pair is the identity.
//
//drops:schema table=PostTags name=post_tags
type PostTag struct {
	PostID int64 `drop:"post_id,notNull"`
	TagID  int64 `drop:"tag_id,notNull"`
}

// Note is the polymorphic pair, both halves of it. owner_type names
// the table the row is attached to and owner_id the row in it, so the
// same table hangs off anything — which is why the MorphTo field is
// an interface and the MorphMany field is a slice of plain notes.
//
//drops:schema table=Notes name=notes
type Note struct {
	ID        int64  `drop:"id,primaryKey,autoIncrement"`
	Body      string `drop:"body,notNull"`
	OwnerType string `drop:"owner_type,notNull"`
	OwnerID   int64  `drop:"owner_id,notNull"`
}
