// Code generated by dropsgen. DO NOT EDIT.
//
// One struct per eager-load shape, generated from the relation
// declarations. Each struct is what a Find that loads the named
// relations fills: the row struct of the table, plus one field per
// relation, tagged the way the loader looks it up.
//
// Edit the relation declarations and the -shape arguments, not this
// file: a change here is reverted the next time dropsgen runs.

package schemagen

// NotesWithOwner is one row of the "notes" table with owner loaded.
//
// It is what this query fills, and only this query — the relation
// paths below are the ones the struct declares, and under
// StrictLoading a query that loads fewer is refused:
//
//	var rows []NotesWithOwner
//	db.Find(Notes).With("owner").All(ctx, &rows)
//
// The columns come from the embedded NotesRow. Each relation field is
// tagged with the name the loader looks up, and typed the way the
// loader fills it:
//
//   - Owner is an interface: "owner" is MorphTo, and the loaded
//     parent's type varies row by row — the loader stores a
//     pointer to it, so read it with a type switch.
type NotesWithOwner struct {
	NotesRow
	Owner any `drop:"-" dropRel:"owner"`
}

// PostsWithAuthor is one row of the "posts" table with author loaded.
//
// It is what this query fills, and only this query — the relation
// paths below are the ones the struct declares, and under
// StrictLoading a query that loads fewer is refused:
//
//	var rows []PostsWithAuthor
//	db.Find(Posts).With("author").All(ctx, &rows)
//
// The columns come from the embedded PostsRow. Each relation field is
// tagged with the name the loader looks up, and typed the way the
// loader fills it:
//
//   - Author is a pointer: "author" is BelongsTo, and a row whose
//     key matches nothing keeps a nil, which a zero struct could
//     not tell from a real row of zeros.
type PostsWithAuthor struct {
	PostsRow
	Author *UsersRow `drop:"-" dropRel:"author"`
}

// PostsWithAuthorPosts is one row of the "posts" table with author.posts loaded.
//
// It is what this query fills, and only this query — the relation
// paths below are the ones the struct declares, and under
// StrictLoading a query that loads fewer is refused:
//
//	var rows []PostsWithAuthorPosts
//	db.Find(Posts).With("author.posts").All(ctx, &rows)
//
// The columns come from the embedded PostsRow. Each relation field is
// tagged with the name the loader looks up, and typed the way the
// loader fills it:
//
//   - Author is a pointer: "author" is BelongsTo, and a row whose
//     key matches nothing keeps a nil, which a zero struct could
//     not tell from a real row of zeros. It is a shape of its own,
//     carrying posts.
type PostsWithAuthorPosts struct {
	PostsRow
	Author *UsersWithPosts `drop:"-" dropRel:"author"`
}

// PostsWithTags is one row of the "posts" table with tags loaded.
//
// It is what this query fills, and only this query — the relation
// paths below are the ones the struct declares, and under
// StrictLoading a query that loads fewer is refused:
//
//	var rows []PostsWithTags
//	db.Find(Posts).With("tags").All(ctx, &rows)
//
// The columns come from the embedded PostsRow. Each relation field is
// tagged with the name the loader looks up, and typed the way the
// loader fills it:
//
//   - Tags is a slice: "tags" is ManyToMany.
//
// A nil slice is not an empty relation. The loader assigns an empty
// non-nil slice to a parent with no children, so a nil one means no
// query ever filled it.
type PostsWithTags struct {
	PostsRow
	Tags []TagsRow `drop:"-" dropRel:"tags"`
}

// UsersWithNotes is one row of the "users" table with notes loaded.
//
// It is what this query fills, and only this query — the relation
// paths below are the ones the struct declares, and under
// StrictLoading a query that loads fewer is refused:
//
//	var rows []UsersWithNotes
//	db.Find(Users).With("notes").All(ctx, &rows)
//
// The columns come from the embedded UsersRow. Each relation field is
// tagged with the name the loader looks up, and typed the way the
// loader fills it:
//
//   - Notes is a slice: "notes" is MorphMany.
//
// A nil slice is not an empty relation. The loader assigns an empty
// non-nil slice to a parent with no children, so a nil one means no
// query ever filled it.
type UsersWithNotes struct {
	UsersRow
	Notes []NotesRow `drop:"-" dropRel:"notes"`
}

// UsersWithPosts is one row of the "users" table with posts loaded.
//
// It is what this query fills, and only this query — the relation
// paths below are the ones the struct declares, and under
// StrictLoading a query that loads fewer is refused:
//
//	var rows []UsersWithPosts
//	db.Find(Users).With("posts").All(ctx, &rows)
//
// The columns come from the embedded UsersRow. Each relation field is
// tagged with the name the loader looks up, and typed the way the
// loader fills it:
//
//   - Posts is a slice: "posts" is HasMany.
//
// A nil slice is not an empty relation. The loader assigns an empty
// non-nil slice to a parent with no children, so a nil one means no
// query ever filled it.
type UsersWithPosts struct {
	UsersRow
	Posts []PostsRow `drop:"-" dropRel:"posts"`
}

// UsersWithProfile is one row of the "users" table with profile loaded.
//
// It is what this query fills, and only this query — the relation
// paths below are the ones the struct declares, and under
// StrictLoading a query that loads fewer is refused:
//
//	var rows []UsersWithProfile
//	db.Find(Users).With("profile").All(ctx, &rows)
//
// The columns come from the embedded UsersRow. Each relation field is
// tagged with the name the loader looks up, and typed the way the
// loader fills it:
//
//   - Profile is a pointer: "profile" is HasOne, and a parent with
//     no match keeps a nil, which a zero struct could not tell from
//     a real row of zeros.
type UsersWithProfile struct {
	UsersRow
	Profile *ProfilesRow `drop:"-" dropRel:"profile"`
}
