// Code generated by dropsgen. DO NOT EDIT.
//
// One row struct and one insert struct per table the schema
// registers. Edit the table declaration, not this file: a change
// here is reverted the next time dropsgen runs, and a struct that
// disagrees with its table is exactly the drift this generator
// removes.

package schemagen

import "time"

// UsersRow is one row of the "users" table, derived from its
// declaration. Every column is bound, so pg.NewEntity needs no
// exemption; a column that admits NULL is a pointer, because that
// is the field type pg.NewEntity will let it bind to.
type UsersRow struct {
	ID        int64     `drop:"id"`
	Email     string    `drop:"email"`
	Name      string    `drop:"name"`
	Age       *int32    `drop:"age"`
	CreatedAt time.Time `drop:"createdAt"`
}

// UsersInsert is UsersRow without the columns a caller must not
// supply.
//
// Omitted:
//   - id — bigserial
//   - createdAt — has a DEFAULT
//
// A pointer field is a column that admits NULL. Bind it with
// (*pg.Col[T]).ValPtr: a nil writes NULL rather than a zero, and
// the column is still in the INSERT — a column the database is
// the one to fill is not in this struct at all.
type UsersInsert struct {
	Email string `drop:"email"`
	Name  string `drop:"name"`
	Age   *int32 `drop:"age"`
}
