package main

import (
	"bytes"
	"fmt"
	"go/format"
	"text/template"
)

// emitTpl renders the generated file. Each entity contributes a
// constant column list, a typed bind function returning the values in
// the declared order, and a typed scan function that consumes a
// drops.Rows row without reflection.
const emitTpl = `// Code generated by dropsgen. DO NOT EDIT.

package {{.Package}}

import "github.com/bernardoforcillo/drops"
{{range .Entities}}
// {{.StructName}} bindings ----------------------------------------------------

// Cols{{.StructName}} returns the column names in the order
// Bind{{.StructName}} / Scan{{.StructName}} use.
func Cols{{.StructName}}() []string {
	return []string{
{{- range .Fields}}
		"{{.Column}}",
{{- end}}
	}
}

// Bind{{.StructName}} returns r's field values in column order,
// ready to pass to a parameterised INSERT or UPDATE.
func Bind{{.StructName}}(r *{{.StructName}}) []any {
	return []any{
{{- range .Fields}}
		r.{{.GoName}},
{{- end}}
	}
}

// Scan{{.StructName}} scans one row from rows into dest. The row's
// column order must match Cols{{.StructName}}(); use a SELECT that
// lists the columns explicitly via Cols{{.StructName}}() to keep
// them aligned.
func Scan{{.StructName}}(rows drops.Rows, dest *{{.StructName}}) error {
	return rows.Scan(
{{- range .Fields}}
		&dest.{{.GoName}},
{{- end}}
	)
}
{{end}}`

type renderCtx struct {
	Package  string
	Entities []entity
}

// emit renders the generated source as gofmt'd bytes.
func emit(pkg string, entities []entity) ([]byte, error) {
	tpl, err := template.New("dropsgen").Parse(emitTpl)
	if err != nil {
		return nil, fmt.Errorf("internal: bad template: %w", err)
	}
	var buf bytes.Buffer
	if err := tpl.Execute(&buf, renderCtx{Package: pkg, Entities: entities}); err != nil {
		return nil, fmt.Errorf("emit: %w", err)
	}
	out, err := format.Source(buf.Bytes())
	if err != nil {
		// Return the unformatted source so callers can debug the
		// generator. Tests catch this via the golden compare.
		return buf.Bytes(), fmt.Errorf("gofmt: %w", err)
	}
	return out, nil
}
