package main

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

// runIntrospect reads a drops/pg snapshot JSON file and emits one Go
// file per declared table, each containing a struct annotated with
// `drop:` tags ready for AutoEntity. The opposite direction of the
// bind/scan generator.
func runIntrospect(snapshotPath, outDir, pkg string) error {
	raw, err := os.ReadFile(snapshotPath)
	if err != nil {
		return err
	}
	var snap struct {
		Tables map[string]*introspectTable `json:"tables"`
	}
	if err := json.Unmarshal(raw, &snap); err != nil {
		return fmt.Errorf("parse snapshot: %w", err)
	}
	if err := os.MkdirAll(outDir, 0o755); err != nil {
		return err
	}
	if pkg == "" {
		pkg = filepath.Base(outDir)
	}
	names := make([]string, 0, len(snap.Tables))
	for name := range snap.Tables {
		names = append(names, name)
	}
	sort.Strings(names)
	for _, key := range names {
		tbl := snap.Tables[key]
		src, err := emitIntrospectFile(pkg, tbl)
		if err != nil {
			return fmt.Errorf("emit %s: %w", tbl.Name, err)
		}
		file := filepath.Join(outDir, snakeForFile(tbl.Name)+"_drops.go")
		if err := os.WriteFile(file, src, 0o644); err != nil {
			return err
		}
	}
	return nil
}

type introspectTable struct {
	Name              string                          `json:"name"`
	Schema            string                          `json:"schema"`
	Columns           map[string]*introspectColumn    `json:"columns"`
	UniqueConstraints map[string]*introspectUnique    `json:"uniqueConstraints"`
}

type introspectColumn struct {
	Name       string  `json:"name"`
	Type       string  `json:"type"`
	PrimaryKey bool    `json:"primaryKey"`
	NotNull    bool    `json:"notNull"`
	Default    *string `json:"default,omitempty"`
}

type introspectUnique struct {
	Name    string   `json:"name"`
	Columns []string `json:"columns"`
}

// emitIntrospectFile renders the Go source for a single table.
func emitIntrospectFile(pkg string, tbl *introspectTable) ([]byte, error) {
	structName := goIdentFor(tbl.Name)
	cols := orderedColumns(tbl.Columns)
	singleUniqs := singleColumnUniqueSet(tbl.UniqueConstraints)

	needsTime := false
	needsJSON := false
	var fields []string
	for _, c := range cols {
		gtype := sqlToGoType(c.Type)
		switch gtype {
		case "time.Time":
			needsTime = true
		case "json.RawMessage":
			needsJSON = true
		}
		tag := buildDropTag(c, singleUniqs[c.Name])
		fields = append(fields, fmt.Sprintf("\t%s %s `%s`", goIdentFor(c.Name), gtype, tag))
	}

	var b strings.Builder
	b.WriteString("// Code generated by dropsgen introspect. DO NOT EDIT.\n\n")
	fmt.Fprintf(&b, "package %s\n\n", pkg)
	imports := []string{}
	if needsTime {
		imports = append(imports, "\"time\"")
	}
	if needsJSON {
		imports = append(imports, "\"encoding/json\"")
	}
	if len(imports) > 0 {
		b.WriteString("import (\n")
		for _, imp := range imports {
			fmt.Fprintf(&b, "\t%s\n", imp)
		}
		b.WriteString(")\n\n")
	}
	tableLiteral := tbl.Name
	if tbl.Schema != "" && tbl.Schema != "public" {
		tableLiteral = tbl.Schema + "." + tbl.Name
	}
	fmt.Fprintf(&b, "// %s mirrors the %q table — introspected from the schema snapshot.\n",
		structName, tableLiteral)
	fmt.Fprintf(&b, "type %s struct {\n", structName)
	for _, f := range fields {
		b.WriteString(f)
		b.WriteByte('\n')
	}
	b.WriteString("}\n")
	return []byte(b.String()), nil
}

// orderedColumns returns the columns sorted by name so output is
// deterministic across runs. Real schema order is lost in the JSON;
// alphabetical is the next-best choice.
func orderedColumns(m map[string]*introspectColumn) []*introspectColumn {
	out := make([]*introspectColumn, 0, len(m))
	for _, c := range m {
		out = append(out, c)
	}
	sort.Slice(out, func(i, j int) bool {
		if out[i].PrimaryKey != out[j].PrimaryKey {
			return out[i].PrimaryKey
		}
		return out[i].Name < out[j].Name
	})
	return out
}

// singleColumnUniqueSet collects unique constraints that target
// exactly one column so we can stamp `unique` on the matching
// field tag.
func singleColumnUniqueSet(uq map[string]*introspectUnique) map[string]bool {
	out := map[string]bool{}
	for _, u := range uq {
		if len(u.Columns) == 1 {
			out[u.Columns[0]] = true
		}
	}
	return out
}

// buildDropTag composes the drop:"name,opt,opt=val" tag value.
func buildDropTag(c *introspectColumn, isUnique bool) string {
	parts := []string{c.Name}
	if c.PrimaryKey {
		parts = append(parts, "primaryKey")
	}
	if isSerialType(c.Type) {
		parts = append(parts, "autoIncrement")
	}
	if c.NotNull && !c.PrimaryKey {
		parts = append(parts, "notNull")
	}
	if isUnique && !c.PrimaryKey {
		parts = append(parts, "unique")
	}
	if c.Default != nil && *c.Default != "" {
		// Skip serial-family auto defaults — they're implicit in
		// autoIncrement.
		if !(isSerialType(c.Type) && strings.HasPrefix(*c.Default, "nextval(")) {
			parts = append(parts, "default="+*c.Default)
		}
	}
	return `drop:"` + strings.Join(parts, ",") + `"`
}

// sqlToGoType maps a column's SQL type to its canonical Go type.
// Falls back to string for unknown types so the generated source
// still compiles; the user can hand-edit afterwards.
func sqlToGoType(sql string) string {
	low := strings.ToLower(strings.TrimSpace(sql))
	switch {
	case strings.HasPrefix(low, "bigserial"), strings.HasPrefix(low, "bigint"):
		return "int64"
	case strings.HasPrefix(low, "serial"), strings.HasPrefix(low, "integer"), strings.HasPrefix(low, "int4"):
		return "int32"
	case strings.HasPrefix(low, "smallserial"), strings.HasPrefix(low, "smallint"):
		return "int16"
	case strings.HasPrefix(low, "boolean"), low == "bool":
		return "bool"
	case strings.HasPrefix(low, "real"):
		return "float32"
	case strings.HasPrefix(low, "double precision"), strings.HasPrefix(low, "float8"):
		return "float64"
	case strings.HasPrefix(low, "text"),
		strings.HasPrefix(low, "varchar"),
		strings.HasPrefix(low, "char"),
		strings.HasPrefix(low, "uuid"):
		return "string"
	case strings.HasPrefix(low, "timestamp"),
		strings.HasPrefix(low, "date"),
		strings.HasPrefix(low, "time"):
		return "time.Time"
	case strings.HasPrefix(low, "json"):
		return "json.RawMessage"
	case strings.HasPrefix(low, "bytea"):
		return "[]byte"
	}
	return "string"
}

// isSerialType reports whether the SQL type belongs to the
// auto-incrementing serial family.
func isSerialType(sql string) bool {
	switch strings.ToLower(strings.TrimSpace(sql)) {
	case "smallserial", "serial", "bigserial":
		return true
	}
	return false
}

// goIdentFor converts an SQL identifier to a Go identifier — Title-cased,
// without underscores, ID-as-acronym preserved.
func goIdentFor(s string) string {
	if s == "" {
		return ""
	}
	parts := strings.FieldsFunc(s, func(r rune) bool { return r == '_' })
	var b strings.Builder
	for _, p := range parts {
		// Title-case the first letter, keep the rest as the source
		// supplied them (camelCase or kebab tokens come through).
		switch p {
		case "id":
			b.WriteString("ID")
		case "url":
			b.WriteString("URL")
		case "uri":
			b.WriteString("URI")
		case "http":
			b.WriteString("HTTP")
		case "ip":
			b.WriteString("IP")
		default:
			b.WriteString(strings.ToUpper(p[:1]) + p[1:])
		}
	}
	return b.String()
}

// snakeForFile converts an identifier to a filename suffix. Camel
// strings stay intact; the underscore separator is preserved when
// already present.
func snakeForFile(s string) string {
	return strings.ToLower(s)
}
