package main

// relsBridgeTemplate is the program dropsgen compiles against the
// user's schema package to read its relation declarations.
//
// It is the same trick the rows bridge plays and for the same reason:
// a relation is declared by calling a method on a package variable,
// so nothing short of the compiler can say what a table's relations
// are. It prints only what a relation *is* — name, kind, target — and
// leaves every decision about what to generate from that to the
// generator, where a test can reach it.
const relsBridgeTemplate = `// Code generated by dropsgen. DO NOT EDIT.
//
// This program exists for one process lifetime. It imports the schema
// package, walks the tables its Schema function registers, and prints
// each table's relations as JSON.
package main

import (
	"encoding/json"
	"fmt"
	"os"
	"sort"

	"github.com/bernardoforcillo/drops/pg"

	userschema "$IMPORT$"
)

const selfImport = "$IMPORT$"

type table struct {
	Name      string
	Schema    string
	Columns   []string
	Relations []relation
}

// relation is one declared edge. Target is the schema-qualified name
// of the table it points at, empty for a MorphTo — whose target is
// whichever table the row's discriminator names, and so is not one
// table at all.
type relation struct {
	Name   string
	Kind   string
	Target string
}

func main() {
	if err := run(); err != nil {
		fmt.Fprintln(os.Stderr, "dropsgen:", err)
		os.Exit(1)
	}
}

func run() error {
	schema := userschema.Schema()
	if schema == nil {
		return fmt.Errorf("%s.Schema() returned nil", selfImport)
	}
	out := make([]table, 0, len(schema.Tables()))
	for _, t := range schema.Tables() {
		tb := table{Name: t.Name(), Schema: t.Schema()}
		// The column names are here for one check: a relation whose
		// Go field name collides with a column's is legal, and the
		// generated doc comment has to say so.
		for _, c := range t.Columns() {
			tb.Columns = append(tb.Columns, c.Name())
		}
		for _, name := range t.RelationNames() {
			rel := t.Relation(name)
			kind, err := kindName(rel.Kind)
			if err != nil {
				return fmt.Errorf("table %q relation %q: %v", t.Name(), name, err)
			}
			tb.Relations = append(tb.Relations, relation{
				Name:   name,
				Kind:   kind,
				Target: qualify(rel.To),
			})
		}
		out = append(out, tb)
	}
	sort.SliceStable(out, func(i, j int) bool {
		if out[i].Schema != out[j].Schema {
			return out[i].Schema < out[j].Schema
		}
		return out[i].Name < out[j].Name
	})
	return json.NewEncoder(os.Stdout).Encode(out)
}

// kindName spells a RelationKind as the JSON the generator matches
// on. A kind this program does not know is an error rather than a
// default: the generator's whole job is to emit the field shape the
// loader fills, and it cannot do that for a kind neither of them has
// heard of.
func kindName(k pg.RelationKind) (string, error) {
	switch k {
	case pg.HasManyKind:
		return "hasMany", nil
	case pg.HasOneKind:
		return "hasOne", nil
	case pg.BelongsToKind:
		return "belongsTo", nil
	case pg.ManyToManyKind:
		return "manyToMany", nil
	case pg.MorphToKind:
		return "morphTo", nil
	case pg.MorphManyKind:
		return "morphMany", nil
	}
	return "", fmt.Errorf("unknown relation kind %d", int(k))
}

// qualify names a target table the way the generator identifies one,
// which is the same way the rows bridge sorts them.
func qualify(t *pg.Table) string {
	if t == nil {
		return ""
	}
	if t.Schema() != "" {
		return t.Schema() + "." + t.Name()
	}
	return t.Name()
}
`
