package main

// rowsBridgeTemplate is the program dropsgen compiles against the
// user's schema package to read a table declaration.
//
// It is deliberately dull, for the reason the `drops` CLI gives for
// its own bridge: every decision it could make is one the generator
// has already made, and code that only exists inside a temporary
// directory is code no test can reach. The one thing it does that
// cannot be done anywhere else is ask the compiler what Go type each
// column carries — reflect.Type in hand, rendered as the source that
// names it.
const rowsBridgeTemplate = `// Code generated by dropsgen. DO NOT EDIT.
//
// This program exists for one process lifetime. It imports the schema
// package, walks the tables its Schema function registers, and prints
// each column as JSON — including the Go type the column's typed
// handle carries, which only a compiler can answer.
package main

import (
	"encoding/json"
	"fmt"
	"os"
	"reflect"
	"sort"
	"strings"

	userschema "$IMPORT$"
)

// selfImport is the schema package's own import path. A column typed
// with a type that package declares needs no qualifier and no import,
// because the generated file lives in that package.
const selfImport = "$IMPORT$"

type table struct {
	Name    string
	Schema  string
	Columns []column
}

// imp is one import the Go type's spelling needs. Name is the
// package's own name, which is not the last element of Path whenever
// a module carries a major-version suffix: github.com/gofrs/uuid/v5
// is package uuid, and only the compiler knows that.
type imp struct {
	Path string
	Name string
}

type column struct {
	Name       string
	SQLType    string
	GoType     string
	Imports    []imp
	Nullable   bool
	PrimaryKey bool
	HasDefault bool
	Managed    bool
}

func main() {
	if err := run(); err != nil {
		fmt.Fprintln(os.Stderr, "dropsgen:", err)
		os.Exit(1)
	}
}

func run() error {
	schema := userschema.Schema()
	if schema == nil {
		return fmt.Errorf("%s.Schema() returned nil", selfImport)
	}
	out := make([]table, 0, len(schema.Tables()))
	for _, t := range schema.Tables() {
		tb := table{Name: t.Name(), Schema: t.Schema()}
		for _, c := range t.Columns() {
			col := column{
				Name:       c.Name(),
				SQLType:    c.Type().TypeSQL(),
				Nullable:   c.IsNullable(),
				PrimaryKey: c.IsPrimaryKey(),
				HasDefault: c.HasDefault(),
				Managed:    c.IsManaged(),
			}
			if gt := c.GoType(); gt != nil {
				imports := map[string]string{}
				spelling, err := render(gt, imports)
				if err != nil {
					return fmt.Errorf("table %q column %q: %v", t.Name(), c.Name(), err)
				}
				col.GoType = spelling
				col.Imports = sorted(imports)
			}
			tb.Columns = append(tb.Columns, col)
		}
		out = append(out, tb)
	}
	// Declaration order is the columns' order and is meaningful;
	// table order is not, so it is made stable here.
	sort.SliceStable(out, func(i, j int) bool {
		if out[i].Schema != out[j].Schema {
			return out[i].Schema < out[j].Schema
		}
		return out[i].Name < out[j].Name
	})
	return json.NewEncoder(os.Stdout).Encode(out)
}

// render writes a reflect.Type as the Go source that names it and
// records the imports that spelling needs, each by path and by the
// package's own name.
func render(t reflect.Type, imports map[string]string) (string, error) {
	if name := t.Name(); name != "" {
		p := t.PkgPath()
		if p == "" {
			// reflect names the type uint8; byte is the same type
			// and the spelling every drops declaration uses, so
			// []byte does not come out as []uint8.
			if name == "uint8" {
				return "byte", nil
			}
			return name, nil // predeclared: string, int64, bool
		}
		// An instantiated generic carries its type arguments inside
		// the name reflect reports, and reflect names them by package
		// *name*: "Null[time.Time]" says time but not which time.
		// There is no path to import, so a bracketed argument that is
		// qualified at all is one this generator cannot write —
		// sql.Null[string] needs nothing beyond database/sql and is
		// fine, sql.Null[time.Time] is not.
		if i := strings.IndexByte(name, '['); i >= 0 && strings.ContainsAny(name[i:], "./") {
			return "", fmt.Errorf("Go type %s is a generic over a type from another package, and the import that names it cannot be recovered; the struct for it has to be hand-written", t)
		}
		if p == selfImport {
			return name, nil
		}
		q, err := qualifier(t)
		if err != nil {
			return "", err
		}
		imports[p] = q
		return q + "." + name, nil
	}
	switch t.Kind() {
	case reflect.Pointer, reflect.Slice, reflect.Array:
		elem, err := render(t.Elem(), imports)
		if err != nil {
			return "", err
		}
		switch t.Kind() {
		case reflect.Pointer:
			return "*" + elem, nil
		case reflect.Slice:
			return "[]" + elem, nil
		default:
			return fmt.Sprintf("[%d]%s", t.Len(), elem), nil
		}
	}
	return "", fmt.Errorf("Go type %s has no source spelling this generator can write; the struct for it has to be hand-written", t)
}

// qualifier is the name a type's package is referred to by, taken
// from the spelling reflect already prints rather than guessed from
// the import path. The two differ for every module past v1 —
// github.com/gofrs/uuid/v5 is package uuid — and a generated file
// that guessed would say v5.UUID and import something nothing uses.
func qualifier(t reflect.Type) (string, error) {
	full, name := t.String(), t.Name()
	q, ok := strings.CutSuffix(full, "."+name)
	if !ok || !isIdent(q) {
		return "", fmt.Errorf("package %q is imported under a name this generator cannot write; the struct for %s has to be hand-written", t.PkgPath(), t)
	}
	return q, nil
}

// isIdent reports whether s is a legal Go identifier, which is what a
// package qualifier has to be.
func isIdent(s string) bool {
	if s == "" {
		return false
	}
	for i, r := range s {
		alpha := r == '_' || (r >= 'a' && r <= 'z') || (r >= 'A' && r <= 'Z')
		if alpha || (i > 0 && r >= '0' && r <= '9') {
			continue
		}
		return false
	}
	return true
}

// sorted flattens the import set into the order the generator will
// see it, so two runs report one thing.
func sorted(m map[string]string) []imp {
	out := make([]imp, 0, len(m))
	for k, v := range m {
		out = append(out, imp{Path: k, Name: v})
	}
	sort.Slice(out, func(i, j int) bool { return out[i].Path < out[j].Path })
	return out
}
`
