package main

import (
	"context"
	"fmt"
	"os"
	"path/filepath"

	"github.com/bernardoforcillo/drops/pg"
)

// runMigrate applies pending migrations, or rolls the last one back.
//
// The migration set is drizzle-kit's on disk and drizzle-orm's in the
// database, so a set generated by drizzle-kit applies here unchanged
// and a set generated by `drops generate` applies from a TypeScript
// process. Neither tool learns about the other; they agree because
// they agree about the journal and the hash.
func runMigrate(ctx context.Context, args []string) error {
	direction := "up"
	if len(args) > 0 && (args[0] == "up" || args[0] == "down") {
		direction, args = args[0], args[1:]
	}
	fs := newFlagSet("migrate", "apply pending migrations, or roll the last one back with `drops migrate down`")
	dsn := fs.String("dsn", "", "PostgreSQL connection string; defaults to $DROPS_PG_DSN or $DATABASE_URL")
	dir := fs.String("dir", "drizzle", "migration directory")
	allow := fs.Bool("allow-destructive", false, "apply statements that destroy data or objects")
	if err := parseFlags(fs, args); err != nil {
		return err
	}
	if err := requireDSN(*dsn); err != nil {
		return err
	}
	if err := requireMigrationDir(*dir); err != nil {
		return err
	}
	db, closeDB, err := connect(ctx, *dsn)
	if err != nil {
		return err
	}
	defer closeDB()

	if direction == "down" {
		return migrateDown(ctx, db, *dir, *allow)
	}
	return migrateUp(ctx, db, *dir, *allow)
}

func migrateUp(ctx context.Context, db *pg.DB, dir string, allow bool) error {
	m := migratorFor(db, dir)
	status, err := m.Status(ctx)
	if err != nil {
		return err
	}
	entries, err := m.LoadEntries()
	if err != nil {
		return err
	}
	byTag := map[string]pg.DrizzleEntry{}
	for _, e := range entries {
		byTag[e.Tag] = e
	}

	var pending []pg.DrizzleStatus
	var statements []string
	for _, s := range status {
		if s.Applied {
			continue
		}
		pending = append(pending, s)
		statements = append(statements, splitMigration(byTag[s.Tag].SQL)...)
	}
	if len(pending) == 0 {
		fmt.Println("no pending migrations:", len(status), "migration(s) in", dir, "are all applied")
		return nil
	}
	fmt.Printf("%d pending migration(s):\n", len(pending))
	for _, s := range pending {
		fmt.Println("  " + s.Tag)
	}
	printWarnings(os.Stdout, statements)
	if err := guard(os.Stdout, statements, allow); err != nil {
		return err
	}
	if err := m.Up(ctx); err != nil {
		return err
	}
	fmt.Printf("\napplied %d migration(s)\n", len(pending))
	return nil
}

// migrateDown rolls back the most recently applied migration using the
// <tag>.down.sql that `drops generate` wrote beside it.
//
// drizzle-kit has no down direction, so a set that came from it has no
// rollback scripts and this says so rather than inventing the inverse
// of somebody else's SQL.
func migrateDown(ctx context.Context, db *pg.DB, dir string, allow bool) error {
	m := migratorFor(db, dir)
	status, err := m.Status(ctx)
	if err != nil {
		return err
	}
	var target *pg.DrizzleStatus
	for i := len(status) - 1; i >= 0; i-- {
		if status[i].Applied {
			target = &status[i]
			break
		}
	}
	if target == nil {
		return fmt.Errorf("nothing to roll back: no migration from %s is applied", dir)
	}
	path := filepath.Join(dir, target.Tag+".down.sql")
	body, err := os.ReadFile(path)
	if err != nil {
		if os.IsNotExist(err) {
			return fmt.Errorf("%s has no rollback script at %s: `drops generate` writes one unless --no-down was passed, and drizzle-kit never writes one — undo it by hand, or write that file and re-run", target.Tag, path)
		}
		return err
	}
	statements := splitMigration(string(body))
	if len(statements) == 0 {
		return fmt.Errorf("%s is empty, so rolling %s back would do nothing", path, target.Tag)
	}

	fmt.Printf("rolling back %s (%d statement(s)):\n", target.Tag, len(statements))
	for _, s := range statements {
		fmt.Println("  " + oneLine(s))
	}
	if err := guard(os.Stdout, statements, allow); err != nil {
		return err
	}

	// The statements and the bookkeeping commit together: a rollback
	// that ran and was not recorded would be applied again by the next
	// `migrate up`, against a database that has already had it undone.
	if err := db.InTx(ctx, func(tx *pg.DB) error {
		for _, s := range statements {
			if _, err := tx.Exec(ctx, s); err != nil {
				return fmt.Errorf("applying %q: %w", oneLine(s), err)
			}
		}
		return forgetMigration(ctx, tx, target.Hash)
	}); err != nil {
		return err
	}
	fmt.Printf("\nrolled back %s\n", target.Tag)
	return nil
}
