package main

import (
	"context"
	"fmt"
	"go/format"
	"os"
	"sort"
	"strconv"
	"strings"

	"github.com/bernardoforcillo/drops/pg"
)

// runPull introspects a live database and writes the Go schema that
// declares it — the way into drops for a database that already exists.
func runPull(ctx context.Context, args []string) error {
	fs := newFlagSet("pull", "introspect a live database into a Go schema file")
	dsn := fs.String("dsn", "", "PostgreSQL connection string; defaults to $DROPS_PG_DSN or $DATABASE_URL")
	out := fs.String("out", "", "file to write; stdout when empty")
	pkgName := fs.String("package", "schema", "package clause for the generated file")
	pgSchema := fs.String("pg-schema", "public", "PostgreSQL schema to introspect")
	if err := parseFlags(fs, args); err != nil {
		return err
	}
	if err := requireDSN(*dsn); err != nil {
		return err
	}
	db, closeDB, err := connect(ctx, *dsn)
	if err != nil {
		return err
	}
	defer closeDB()

	live, err := pg.Introspect(ctx, db, pg.IntrospectOptions{Schemas: []string{*pgSchema}})
	if err != nil {
		return fmt.Errorf("introspect: %w", err)
	}
	if len(live.Tables) == 0 {
		return fmt.Errorf("schema %q has no tables to pull", *pgSchema)
	}
	src, err := renderGoSchema(live, *pkgName)
	if err != nil {
		return err
	}
	if *out == "" {
		_, err = os.Stdout.Write(src)
		return err
	}
	if err := os.WriteFile(*out, src, 0o644); err != nil {
		return err
	}
	fmt.Printf("wrote %s: %d table(s)\n", *out, len(live.Tables))
	fmt.Println("edit it, commit it, and pass it to `drops generate --schema` from now on")
	return nil
}

// renderGoSchema turns a snapshot into compilable Go declaring the
// same tables.
//
// What it cannot render it says so about, in a comment in the output,
// rather than rendering something close: a partial index whose
// predicate exists only as text in the catalogue would come back as an
// index over the whole table, which is a different index under the
// same name — the exact confusion the snapshot format goes out of its
// way to avoid.
func renderGoSchema(snap *pg.Snapshot, pkgName string) ([]byte, error) {
	var b strings.Builder
	b.WriteString("// Generated by `drops pull` from a live database.\n")
	b.WriteString("//\n")
	b.WriteString("// This is a starting point, not a generated artefact: edit it, commit\n")
	b.WriteString("// it, and let it be the schema of record. This generator renders\n")
	b.WriteString("// tables, columns, keys, uniques, checks, indexes and single-column\n")
	b.WriteString("// foreign keys. Enums, sequences, views, row-level security and\n")
	b.WriteString("// policies are read back by Introspect but not declared below, and a\n")
	b.WriteString("// multi-column foreign key is not read back at all — declare those by\n")
	b.WriteString("// hand before pushing, or the first push proposes to drop them.\n")
	b.WriteString("//\n")
	b.WriteString("// drops names foreign keys itself, so one PostgreSQL named — the\n")
	b.WriteString("// usual <table>_<column>_fkey — is dropped and re-created under the\n")
	b.WriteString("// derived name the first time this schema is pushed or migrated. The\n")
	b.WriteString("// constraint is the same constraint; only the name changes.\n")
	b.WriteString("package " + pkgName + "\n\n")
	b.WriteString("import \"github.com/bernardoforcillo/drops/pg\"\n\n")

	keys := sortedKeysOf(snap.Tables)
	tableVar := map[string]string{}  // snapshot key   -> Go identifier
	colVar := map[string]string{}    // "table.column" -> Go identifier
	colGoType := map[string]string{} // "table.column" -> Go value type
	taken := map[string]bool{"Schema": true}

	for _, key := range keys {
		t := snap.Tables[key]
		tableVar[key] = uniqueIdent(goIdent(t.Name), taken)
	}
	for _, key := range keys {
		t := snap.Tables[key]
		for _, name := range sortedKeysOf(t.Columns) {
			ident := uniqueIdent(tableVar[key]+goIdent(name), taken)
			colVar[t.Name+"."+name] = ident
			colGoType[t.Name+"."+name] = goValueType(t.Columns[name].Type)
		}
	}

	var deferred []string // table-level declarations, emitted in init()
	for _, key := range keys {
		t := snap.Tables[key]
		fmt.Fprintf(&b, "// %s is the %q table.\n", tableVar[key], t.Name)
		b.WriteString("var (\n")
		if t.Schema != "" && t.Schema != "public" {
			fmt.Fprintf(&b, "\t%s = pg.NewSchemaTable(%q, %q)\n", tableVar[key], t.Schema, t.Name)
		} else {
			fmt.Fprintf(&b, "\t%s = pg.NewTable(%q)\n", tableVar[key], t.Name)
		}
		for _, name := range sortedKeysOf(t.Columns) {
			col := t.Columns[name]
			fmt.Fprintf(&b, "\t%s = pg.Add(%s, %s)\n",
				colVar[t.Name+"."+name], tableVar[key],
				columnExpr(t, col, colVar, colGoType, &deferred))
		}
		b.WriteString(")\n\n")
		deferred = append(deferred, tableExtras(t, tableVar[key], colVar)...)
	}

	if len(deferred) > 0 {
		b.WriteString("// Everything a column declaration cannot carry: composite keys,\n")
		b.WriteString("// named constraints and indexes. init runs once, so the table is\n")
		b.WriteString("// declared exactly as often as it is used.\n")
		b.WriteString("func init() {\n")
		for _, line := range deferred {
			b.WriteString("\t" + line + "\n")
		}
		b.WriteString("}\n\n")
	}

	b.WriteString("// Schema is the set of tables drops manages. `drops generate`,\n")
	b.WriteString("// `drops push` and `drops drift` all call it by name.\n")
	b.WriteString("func Schema() *pg.Schema {\n\treturn pg.NewSchema(\n")
	for _, key := range keys {
		fmt.Fprintf(&b, "\t\t%s,\n", tableVar[key])
	}
	b.WriteString("\t)\n}\n")

	src, err := format.Source([]byte(b.String()))
	if err != nil {
		return nil, fmt.Errorf("the generated schema is not valid Go (%w); this is a bug in drops pull, and the unformatted source follows:\n%s", err, b.String())
	}
	return src, nil
}

// columnExpr renders one pg.Add argument.
func columnExpr(t *pg.TableSnapshot, col *pg.ColumnSnapshot,
	colVar, colGoType map[string]string, deferred *[]string) string {
	var b strings.Builder
	b.WriteString(constructor(col.Type, col.Name))
	if col.PrimaryKey {
		b.WriteString(".PrimaryKey()")
	} else if col.NotNull {
		// A primary key is NOT NULL by definition and PrimaryKey()
		// already says so; adding NotNull() would render it twice.
		b.WriteString(".NotNull()")
	}
	if col.Default != nil && *col.Default != "" {
		fmt.Fprintf(&b, ".Default(%q)", *col.Default)
	}
	if fk := singleColumnFK(t, col.Name); fk != nil {
		target := fk.TableTo + "." + fk.ColumnsTo[0]
		targetVar, known := colVar[target]
		switch {
		case !known:
			*deferred = append(*deferred, fmt.Sprintf(
				"// %s.%s references %s, which this schema does not contain — declare it and add .References().",
				t.Name, col.Name, target))
		case colGoType[target] != colGoType[t.Name+"."+col.Name]:
			// References is typed: both columns have to carry the same
			// Go value type or the generated file will not compile.
			*deferred = append(*deferred, fmt.Sprintf(
				"// %s.%s references %s, whose Go type is %s rather than %s — reconcile the two column types, then add .References().",
				t.Name, col.Name, target, colGoType[target], colGoType[t.Name+"."+col.Name]))
		default:
			b.WriteString(".References(" + targetVar + referentialActions(fk) + ")")
		}
	}
	return b.String()
}

// referentialActions renders the ON DELETE / ON UPDATE options, if the
// constraint carries any beyond the default.
func referentialActions(fk *pg.ForeignKeySnapshot) string {
	var out strings.Builder
	if a := strings.ToUpper(fk.OnDelete); a != "" && a != "NO ACTION" {
		fmt.Fprintf(&out, ", pg.OnDelete(%q)", a)
	}
	if a := strings.ToUpper(fk.OnUpdate); a != "" && a != "NO ACTION" {
		fmt.Fprintf(&out, ", pg.OnUpdate(%q)", a)
	}
	return out.String()
}

// singleColumnFK returns the foreign key that covers exactly this
// column, if there is one.
func singleColumnFK(t *pg.TableSnapshot, column string) *pg.ForeignKeySnapshot {
	for _, name := range sortedKeysOf(t.ForeignKeys) {
		fk := t.ForeignKeys[name]
		if len(fk.ColumnsFrom) == 1 && len(fk.ColumnsTo) == 1 && fk.ColumnsFrom[0] == column {
			return fk
		}
	}
	return nil
}

// tableExtras renders the declarations that hang off the table rather
// than off one column.
func tableExtras(t *pg.TableSnapshot, tableVar string, colVar map[string]string) []string {
	var out []string
	ref := func(column string) (string, bool) {
		v, ok := colVar[t.Name+"."+column]
		return v, ok
	}
	for _, name := range sortedKeysOf(t.CompositePrimaryKeys) {
		pk := t.CompositePrimaryKeys[name]
		// The snapshot records a key of one column in both places:
		// here, because that is the list Diff compares, and on the
		// column, because that is drizzle-kit's spelling. columnExpr
		// has already written the column's `.PrimaryKey()`, so writing
		// the table-level form too would declare one key twice.
		if len(pk.Columns) == 1 {
			if c, ok := t.Columns[pk.Columns[0]]; ok && c.PrimaryKey {
				continue
			}
		}
		if args, ok := refList(pk.Columns, ref); ok {
			out = append(out, fmt.Sprintf("%s.PrimaryKey(%s)", tableVar, args))
		}
	}
	for _, name := range sortedKeysOf(t.UniqueConstraints) {
		u := t.UniqueConstraints[name]
		if args, ok := refList(u.Columns, ref); ok {
			out = append(out, fmt.Sprintf("%s.AddUnique(%q, %s)", tableVar, u.Name, args))
		}
	}
	for _, name := range sortedKeysOf(t.CheckConstraints) {
		c := t.CheckConstraints[name]
		out = append(out, fmt.Sprintf("%s.AddCheck(%q, %q)", tableVar, c.Name, c.Value))
	}
	for _, name := range sortedKeysOf(t.Indexes) {
		idx := t.Indexes[name]
		if len(idx.Columns) == 0 {
			out = append(out, fmt.Sprintf(
				"// index %q on %q is over an expression rather than plain columns; declare it with pg.NewIndex and pg.CreateIndex.",
				name, t.Name))
			continue
		}
		if idx.Where != "" {
			out = append(out, fmt.Sprintf(
				"// index %q on %q is partial (WHERE %s); its predicate is SQL text here and an expression in Go, so declare it by hand.",
				name, t.Name, idx.Where))
			continue
		}
		args, ok := refList(idx.Columns, ref)
		if !ok {
			continue
		}
		var line strings.Builder
		fmt.Fprintf(&line, "%s.AddIndex(pg.NewIndex(%q, %s, %s)", tableVar, idx.Name, tableVar, args)
		if idx.IsUnique {
			line.WriteString(".Unique()")
		}
		if idx.Method != "" && idx.Method != "btree" {
			fmt.Fprintf(&line, ".Using(%q)", idx.Method)
		}
		if len(idx.Include) > 0 {
			if inc, ok := refList(idx.Include, ref); ok {
				fmt.Fprintf(&line, ".Include(%s)", inc)
			}
		}
		line.WriteString(")")
		out = append(out, line.String())
	}
	return out
}

// refList renders column identifiers as an argument list, reporting
// false when any of them is unknown.
func refList(columns []string, ref func(string) (string, bool)) (string, bool) {
	idents := make([]string, 0, len(columns))
	for _, c := range columns {
		v, ok := ref(c)
		if !ok {
			return "", false
		}
		idents = append(idents, v)
	}
	return strings.Join(idents, ", "), true
}

// constructor maps a snapshot type to the pg constructor that declares
// it. An unrecognised type goes through pg.Custom, which renders the
// type literally — so a domain, an extension type or an enum survives
// the round trip even though nothing here understands it.
func constructor(typeSQL, name string) string {
	base, args := splitTypeArgs(typeSQL)
	quoted := strconv.Quote(name)
	switch base {
	case "text":
		return "pg.Text(" + quoted + ")"
	case "varchar", "character varying":
		return fmt.Sprintf("pg.Varchar(%s, %d)", quoted, firstArg(args))
	case "char", "bpchar", "character":
		return fmt.Sprintf("pg.Char(%s, %d)", quoted, firstArg(args))
	case "smallint":
		return "pg.SmallInt(" + quoted + ")"
	case "integer":
		return "pg.Integer(" + quoted + ")"
	case "bigint":
		return "pg.BigInt(" + quoted + ")"
	case "smallserial":
		return "pg.SmallSerial(" + quoted + ")"
	case "serial":
		return "pg.Serial(" + quoted + ")"
	case "bigserial":
		return "pg.BigSerial(" + quoted + ")"
	case "real":
		return "pg.Real(" + quoted + ")"
	case "double precision":
		return "pg.DoublePrecision(" + quoted + ")"
	case "numeric", "decimal":
		precision, scale := firstArg(args), secondArg(args)
		return fmt.Sprintf("pg.Numeric(%s, %d, %d)", quoted, precision, scale)
	case "boolean":
		return "pg.Boolean(" + quoted + ")"
	case "date":
		return "pg.Date(" + quoted + ")"
	case "time":
		return "pg.Time(" + quoted + ")"
	case "timestamp":
		return fmt.Sprintf("pg.Timestamp(%s, false)", quoted)
	case "timestamptz":
		return fmt.Sprintf("pg.Timestamp(%s, true)", quoted)
	case "interval":
		return "pg.Interval(" + quoted + ")"
	case "uuid":
		return "pg.UUID(" + quoted + ")"
	case "json":
		return "pg.JSON(" + quoted + ")"
	case "jsonb":
		return "pg.JSONB(" + quoted + ")"
	case "bytea":
		return "pg.Bytea(" + quoted + ")"
	}
	// Anything else — a domain, an enum, an extension type — keeps its
	// type literal and is scanned as text, which is what PostgreSQL
	// sends for a type this package has no opinion about.
	return fmt.Sprintf("pg.Custom[string](%s, %s)", quoted, strconv.Quote(typeSQL))
}

// goValueType is the Go type a column scans into — the type parameter
// of its *pg.Col, which is what makes References type-check.
func goValueType(typeSQL string) string {
	base, _ := splitTypeArgs(typeSQL)
	switch base {
	case "smallint", "smallserial":
		return "int16"
	case "integer", "serial":
		return "int32"
	case "bigint", "bigserial":
		return "int64"
	case "real":
		return "float32"
	case "double precision":
		return "float64"
	case "boolean":
		return "bool"
	case "date", "time", "timestamp", "timestamptz":
		return "time.Time"
	case "json", "jsonb":
		return "json.RawMessage"
	case "bytea":
		return "[]byte"
	}
	return "string"
}

// splitTypeArgs separates "numeric(10,2)" into "numeric" and
// ["10", "2"].
func splitTypeArgs(typeSQL string) (string, []string) {
	open := strings.IndexByte(typeSQL, '(')
	if open < 0 || !strings.HasSuffix(typeSQL, ")") {
		return strings.ToLower(strings.TrimSpace(typeSQL)), nil
	}
	base := strings.ToLower(strings.TrimSpace(typeSQL[:open]))
	inner := typeSQL[open+1 : len(typeSQL)-1]
	var args []string
	for _, part := range strings.Split(inner, ",") {
		args = append(args, strings.TrimSpace(part))
	}
	return base, args
}

func firstArg(args []string) int {
	if len(args) == 0 {
		return 0
	}
	n, _ := strconv.Atoi(args[0])
	return n
}

func secondArg(args []string) int {
	if len(args) < 2 {
		return 0
	}
	n, _ := strconv.Atoi(args[1])
	return n
}

// goIdent turns a SQL identifier into an exported Go one.
func goIdent(name string) string {
	var b strings.Builder
	upper := true
	for _, r := range name {
		switch {
		case r >= 'a' && r <= 'z', r >= 'A' && r <= 'Z':
			if upper {
				b.WriteRune(toUpper(r))
				upper = false
				continue
			}
			b.WriteRune(r)
		case r >= '0' && r <= '9':
			if b.Len() == 0 {
				// A Go identifier cannot start with a digit.
				b.WriteByte('T')
			}
			b.WriteRune(r)
			upper = false
		default:
			upper = true
		}
	}
	if b.Len() == 0 {
		return "Table"
	}
	return b.String()
}

func toUpper(r rune) rune {
	if r >= 'a' && r <= 'z' {
		return r - ('a' - 'A')
	}
	return r
}

// uniqueIdent keeps two SQL names that collapse to one Go identifier
// from colliding in the generated file.
func uniqueIdent(base string, taken map[string]bool) string {
	candidate := base
	for i := 2; taken[candidate]; i++ {
		candidate = base + strconv.Itoa(i)
	}
	taken[candidate] = true
	return candidate
}

func sortedKeysOf[V any](m map[string]V) []string {
	out := make([]string, 0, len(m))
	for k := range m {
		out = append(out, k)
	}
	sort.Strings(out)
	return out
}
