package pg

import (
	"context"
	"sync/atomic"
)

// Factory builds and inserts test rows for an Entity. The template
// callback returns a fresh value each call; the supplied seq is a
// monotonically increasing counter the template can interpolate into
// fields that need to stay unique across a batch.
//
//	var PlayerFactory = pg.NewFactory(PlayerEntity, func(seq int) Player {
//	    return Player{
//	        Name:      fmt.Sprintf("player-%d", seq),
//	        Level:     1,
//	        Region:    "eu",
//	        CreatedAt: time.Now(),
//	    }
//	})
//
//	// In a test
//	p, _ := PlayerFactory.Create(ctx, db)             // one row, inserted
//	ps, _ := PlayerFactory.CreateN(ctx, db, 100)     // batch insert
//	admin := PlayerFactory.With(func(p *Player) { p.Role = "admin" })
//	a, _ := admin.Create(ctx, db)
//
// Factories are safe to share across goroutines — the sequence
// counter is atomic. Call Reset between subtests if you need
// stable identifiers.
type Factory[T any] struct {
	entity   *Entity[T]
	template func(seq int) T
	seq      *atomic.Int64
}

// NewFactory binds template to entity. The template fires once per
// Build / Create call; the seq it receives is the post-increment
// counter so the first invocation sees seq=1.
func NewFactory[T any](e *Entity[T], template func(seq int) T) *Factory[T] {
	return &Factory[T]{entity: e, template: template, seq: new(atomic.Int64)}
}

// Build returns a fresh value without touching the database.
func (f *Factory[T]) Build() T {
	n := int(f.seq.Add(1))
	return f.template(n)
}

// BuildN returns n freshly templated values without touching the
// database. Each value receives a distinct seq.
func (f *Factory[T]) BuildN(n int) []T {
	out := make([]T, n)
	for i := 0; i < n; i++ {
		out[i] = f.Build()
	}
	return out
}

// Create builds one value and inserts it. The returned T reflects
// any server-side defaults / autogenerated PK fields the entity
// scans back.
func (f *Factory[T]) Create(ctx context.Context, db *DB) (T, error) {
	v := f.Build()
	err := f.entity.Create(db, ctx, &v)
	return v, err
}

// CreateN builds n values and inserts them in a single statement
// via Entity.CreateMany — vastly cheaper than N Create calls when
// seeding wide test fixtures. Returns the templated values; note
// that autogenerated PKs are not currently read back from the
// batch path (matches Entity.CreateMany's semantics).
func (f *Factory[T]) CreateN(ctx context.Context, db *DB, n int) ([]T, error) {
	rows := f.BuildN(n)
	if _, err := f.entity.CreateMany(db, ctx, rows); err != nil {
		return nil, err
	}
	return rows, nil
}

// With returns a child factory whose Build / Create calls run the
// parent template, then apply mutate to the result. Use it to spin
// off variant factories — admins, banned players, expired sessions
// — without redeclaring the whole template.
//
// Child factories share the parent's sequence counter so identifiers
// remain unique across both. Call WithSequence to start a new one.
func (f *Factory[T]) With(mutate func(*T)) *Factory[T] {
	return &Factory[T]{
		entity: f.entity,
		template: func(seq int) T {
			v := f.template(seq)
			mutate(&v)
			return v
		},
		seq: f.seq,
	}
}

// Reset rewinds the sequence counter to zero. Typically called in
// test setup between subtests so identifiers stay stable from one
// run to the next.
func (f *Factory[T]) Reset() { f.seq.Store(0) }

// Sequence returns the current sequence value without advancing.
// Useful for assertions on factory state in test helpers.
func (f *Factory[T]) Sequence() int { return int(f.seq.Load()) }

// Entity returns the underlying Entity[T] handle. Tests that need
// to call entity-level helpers (Find, Delete, ...) skip the
// indirection through the factory.
func (f *Factory[T]) Entity() *Entity[T] { return f.entity }
