package pg

import (
	"errors"
	"fmt"
	"strings"
)

// Renaming, and why it has to be declared.
//
// A dropped column and an added column are the same thing to a diff:
// two snapshots, one name missing from the newer, one name new in it.
// Only the author knows the pair is one column wearing a new name, and
// the difference between the two readings is the entire contents of the
// column. Every tool that guesses gets it wrong somewhere — atlas
// infers the pair heuristically and mispairs on a symmetric table,
// GORM adds the new column and leaves the old one for ever,
// drizzle-kit asks a terminal, which CI does not have and which leaves
// no artefact a reviewer can read afterwards.
//
// So drops asks the author, in the one place someone will look at it
// again: the call site. A []Rename is Go values, checked by the
// compiler, visible in the diff of the pull request that performs the
// rename, and identical on a laptop and in CI.
//
// Only drops/pg implements renames. drops/sqlite deliberately does not:
// its diff rebuilds a table to change it, so a rename would have to
// feed the rebuild's INSERT ... SELECT column pairing, and a pairing
// that is off by one silently moves every value into the neighbouring
// column. drops/mysql does not either: RENAME COLUMN arrived in MySQL
// 8.0 and MariaDB 10.5, and the CHANGE COLUMN form every older server
// needs restates the column's full definition, so the statement that
// renames it also silently retypes it if the restatement is wrong.

// RenameKind says which kind of object a Rename is about.
type RenameKind string

const (
	// RenameSchema renames a PostgreSQL schema, moving every table in
	// it. From and To are schema names; Table is ignored.
	RenameSchema RenameKind = "schema"
	// RenameTable renames a table. From and To are table names,
	// optionally schema-qualified as "schema.table"; Table is ignored.
	RenameTable RenameKind = "table"
	// RenameColumn renames a column of Table. From and To are column
	// names; Table is required.
	RenameColumn RenameKind = "column"
)

// Rename declares that a drop and an add in the diff are one object
// under a new name.
//
// Pass them through GenerateOptions.Renames. They are applied in the
// order given, before the diff runs, and each one names its objects as
// they stand at that point in the sequence — so a Rename that moves a
// column of a table an earlier Rename has already renamed must use the
// table's new name, exactly as the DDL it generates would have to.
type Rename struct {
	// Kind selects what is being renamed. Required.
	Kind RenameKind
	// Table names the table a RenameColumn applies to, optionally
	// schema-qualified as "schema.table". Required for RenameColumn,
	// ignored for the other kinds.
	Table string
	// From is the current name, To the new one. Both required, and
	// they have to differ.
	From, To string
}

// ErrRenameNotApplicable is returned when a declared rename matches no
// change in the diff: the object it renames is not there under the old
// name, or is already there under the new one. It fires most often
// because the rename was generated by an earlier migration and the
// declaration was left behind in the call — running it a second time
// would rename something else, or nothing.
var ErrRenameNotApplicable = errors.New("drops/pg: rename matches no change in the diff")

// ErrRenameInvalid is returned when a Rename is not a description of
// anything: an unknown Kind, an empty From or To, the two equal, or a
// RenameColumn with no Table. It is a mistake at the call site rather
// than a disagreement with the schema, so it is reported separately
// from ErrRenameNotApplicable — the fix is different.
var ErrRenameInvalid = errors.New("drops/pg: rename is incomplete")

// renamePlan is what a set of declared renames turns into: the previous
// snapshot rewritten as though the renames had already happened, the
// DDL that performs them, the DDL that undoes them, and the record of
// them written into the new snapshot's _meta.
type renamePlan struct {
	prev *Snapshot
	up   []string
	down []string
	meta SnapshotMeta
}

// applyRenames rewrites prev as though every declared rename had
// already been applied to it, and returns the DDL that performs them.
//
// Rewriting the previous side rather than post-processing the diff is
// what makes the rest of the generator unaware that renames exist: once
// prev calls the column by its new name, the drop and the add are
// simply not in the diff, and a change that came along with the rename
// — a widened type, a dropped NOT NULL — still is, as an ALTER on the
// new name. Nothing has to recognise a drop/add pair after the fact.
//
// The rewrite copies what it touches; prev is left as the caller had
// it, because the caller wrote it to disk under an index of its own and
// a snapshot that quietly disagreed with its file would corrupt every
// diff after this one.
//
// References follow the object, the way PostgreSQL's own catalogue
// does: renaming a column rewrites it inside that table's indexes,
// unique constraints, primary key and foreign keys, and inside the
// foreign keys of every table pointing at it. Without that the diff
// would drop and rebuild an index over the renamed column — on a table
// large enough to have wanted the index — to arrive at the index it
// already has. A CHECK constraint is the exception: its expression is
// opaque SQL text, so one naming the renamed column compares unequal
// and is dropped and re-added, which is correct if noisier than it
// needs to be.
func applyRenames(prev, cur *Snapshot, renames []Rename) (*renamePlan, error) {
	plan := &renamePlan{
		prev: prev,
		meta: SnapshotMeta{
			Columns: map[string]any{},
			Schemas: map[string]any{},
			Tables:  map[string]any{},
		},
	}
	if len(renames) == 0 {
		return plan, nil
	}
	if cur == nil {
		cur = EmptySnapshot()
	}
	plan.prev = cloneSnapshotTables(prev)

	for _, r := range renames {
		if err := validateRename(r); err != nil {
			return nil, err
		}
		var (
			up, down string
			err      error
		)
		switch r.Kind {
		case RenameSchema:
			up, down, err = renameSchemaIn(plan, cur, r)
		case RenameTable:
			up, down, err = renameTableIn(plan, cur, r)
		case RenameColumn:
			up, down, err = renameColumnIn(plan, cur, r)
		}
		if err != nil {
			return nil, err
		}
		plan.up = append(plan.up, up)
		// The undo runs in reverse: the last rename applied is the
		// first one taken back, so every statement in the down
		// direction sees the names its own rename left behind.
		plan.down = append([]string{down}, plan.down...)
	}
	return plan, nil
}

// validateRename rejects a Rename that describes nothing.
func validateRename(r Rename) error {
	switch r.Kind {
	case RenameSchema, RenameTable, RenameColumn:
	default:
		return fmt.Errorf("%w: %+v has kind %q, want one of %q, %q, %q",
			ErrRenameInvalid, r, r.Kind, RenameSchema, RenameTable, RenameColumn)
	}
	if r.From == "" || r.To == "" {
		return fmt.Errorf("%w: %+v leaves From or To empty", ErrRenameInvalid, r)
	}
	if r.From == r.To {
		return fmt.Errorf("%w: %+v renames %q to itself", ErrRenameInvalid, r, r.From)
	}
	if r.Kind == RenameColumn && r.Table == "" {
		return fmt.Errorf("%w: %+v renames a column without naming its table", ErrRenameInvalid, r)
	}
	return nil
}

// renameColumnIn moves one column of one table to its new name.
func renameColumnIn(plan *renamePlan, cur *Snapshot, r Rename) (string, string, error) {
	key, _, _ := splitTableRef(r.Table)
	pt, ok := plan.prev.Tables[key]
	if !ok {
		return "", "", fmt.Errorf("%w: %+v names table %q, which the previous snapshot does not have",
			ErrRenameNotApplicable, r, key)
	}
	ct, ok := cur.Tables[key]
	if !ok {
		return "", "", fmt.Errorf("%w: %+v names table %q, which the Go schema does not declare",
			ErrRenameNotApplicable, r, key)
	}
	pc, ok := pt.Columns[r.From]
	if !ok {
		return "", "", fmt.Errorf("%w: %+v renames %q.%q, which the previous snapshot does not have",
			ErrRenameNotApplicable, r, key, r.From)
	}
	if _, ok := pt.Columns[r.To]; ok {
		return "", "", fmt.Errorf("%w: %+v renames %q.%q onto %q, which the previous snapshot already has",
			ErrRenameNotApplicable, r, key, r.From, r.To)
	}
	if _, ok := ct.Columns[r.To]; !ok {
		return "", "", fmt.Errorf("%w: %+v renames %q.%q to %q, which the Go schema does not declare",
			ErrRenameNotApplicable, r, key, r.From, r.To)
	}
	if _, ok := ct.Columns[r.From]; ok {
		return "", "", fmt.Errorf("%w: %+v renames %q.%q away, but the Go schema still declares it",
			ErrRenameNotApplicable, r, key, r.From)
	}

	delete(pt.Columns, r.From)
	pc.Name = r.To
	pt.Columns[r.To] = pc
	renameColumnRefs(plan.prev, pt, r.From, r.To)
	plan.meta.Columns[key+"."+r.From] = key + "." + r.To

	table := qualifiedTableSQL(pt)
	return fmt.Sprintf(`ALTER TABLE %s RENAME COLUMN %s TO %s;`, table, quoteIdent(r.From), quoteIdent(r.To)),
		fmt.Sprintf(`ALTER TABLE %s RENAME COLUMN %s TO %s;`, table, quoteIdent(r.To), quoteIdent(r.From)),
		nil
}

// renameTableIn moves one table to its new name, within its schema.
func renameTableIn(plan *renamePlan, cur *Snapshot, r Rename) (string, string, error) {
	fromKey, schema, fromName := splitTableRef(r.From)
	toKey, _, toName := splitTableRef(qualifyLike(r.To, schema))
	pt, ok := plan.prev.Tables[fromKey]
	if !ok {
		return "", "", fmt.Errorf("%w: %+v renames table %q, which the previous snapshot does not have",
			ErrRenameNotApplicable, r, fromKey)
	}
	if _, ok := plan.prev.Tables[toKey]; ok {
		return "", "", fmt.Errorf("%w: %+v renames %q onto %q, which the previous snapshot already has",
			ErrRenameNotApplicable, r, fromKey, toKey)
	}
	if _, ok := cur.Tables[toKey]; !ok {
		return "", "", fmt.Errorf("%w: %+v renames %q to %q, which the Go schema does not declare",
			ErrRenameNotApplicable, r, fromKey, toKey)
	}
	if _, ok := cur.Tables[fromKey]; ok {
		return "", "", fmt.Errorf("%w: %+v renames %q away, but the Go schema still declares it",
			ErrRenameNotApplicable, r, fromKey)
	}

	source := qualifiedTableSQL(pt)
	delete(plan.prev.Tables, fromKey)
	pt.Name = toName
	plan.prev.Tables[toKey] = pt
	renameTableRefs(plan.prev, fromName, toName)
	plan.meta.Tables[fromKey] = toKey

	// PostgreSQL takes the new name unqualified — the table cannot
	// change schema on the way — and the down direction addresses it
	// under the name the up direction gave it.
	return fmt.Sprintf(`ALTER TABLE %s RENAME TO %s;`, source, quoteIdent(toName)),
		fmt.Sprintf(`ALTER TABLE %s RENAME TO %s;`, qualifiedTableSQL(pt), quoteIdent(fromName)),
		nil
}

// renameSchemaIn moves every table of one schema into another name.
//
// Diff renders no CREATE SCHEMA and no DROP SCHEMA, so a schema rename
// is not visible as a pair of statements the way the other two kinds
// are. What it is visible as is every table in the schema being dropped
// and recreated, because a snapshot keys its tables by "schema.table" —
// which is exactly the data loss this file exists to prevent.
func renameSchemaIn(plan *renamePlan, cur *Snapshot, r Rename) (string, string, error) {
	moved := tablesInSchema(plan.prev, r.From)
	if len(moved) == 0 {
		return "", "", fmt.Errorf("%w: %+v renames schema %q, which holds no table in the previous snapshot",
			ErrRenameNotApplicable, r, r.From)
	}
	if len(tablesInSchema(cur, r.To)) == 0 {
		return "", "", fmt.Errorf("%w: %+v renames schema %q to %q, and the Go schema declares no table in %q",
			ErrRenameNotApplicable, r, r.From, r.To, r.To)
	}
	if len(tablesInSchema(cur, r.From)) > 0 {
		return "", "", fmt.Errorf("%w: %+v renames schema %q away, but the Go schema still declares tables in it",
			ErrRenameNotApplicable, r, r.From)
	}

	for _, key := range moved {
		t := plan.prev.Tables[key]
		delete(plan.prev.Tables, key)
		t.Schema = r.To
		plan.prev.Tables[r.To+"."+t.Name] = t
		for _, fk := range t.ForeignKeys {
			if fk.SchemaTo == r.From {
				fk.SchemaTo = r.To
			}
		}
	}
	plan.meta.Schemas[r.From] = r.To

	return fmt.Sprintf(`ALTER SCHEMA %s RENAME TO %s;`, quoteIdent(r.From), quoteIdent(r.To)),
		fmt.Sprintf(`ALTER SCHEMA %s RENAME TO %s;`, quoteIdent(r.To), quoteIdent(r.From)),
		nil
}

// tablesInSchema returns the keys of every table a snapshot puts in the
// named schema, sorted, so the rewrite is deterministic.
func tablesInSchema(s *Snapshot, schema string) []string {
	var out []string
	for _, key := range sortedKeys(s.Tables) {
		if schemaOf(s.Tables[key]) == schema {
			out = append(out, key)
		}
	}
	return out
}

// schemaOf answers with the schema a table snapshot is in, filling in
// the default the way tableKey does — an empty Schema is "public", not
// a schema with no name.
func schemaOf(t *TableSnapshot) string {
	if t.Schema == "" {
		return "public"
	}
	return t.Schema
}

// renameColumnRefs rewrites every place inside the snapshot that names
// the column by position rather than by expression.
func renameColumnRefs(s *Snapshot, t *TableSnapshot, from, to string) {
	for _, idx := range t.Indexes {
		replaceString(idx.Columns, from, to)
		replaceString(idx.Include, from, to)
	}
	for _, u := range t.UniqueConstraints {
		replaceString(u.Columns, from, to)
	}
	for _, pk := range t.CompositePrimaryKeys {
		replaceString(pk.Columns, from, to)
	}
	for _, fk := range t.ForeignKeys {
		replaceString(fk.ColumnsFrom, from, to)
	}
	for _, other := range s.Tables {
		for _, fk := range other.ForeignKeys {
			if fk.TableTo == t.Name {
				replaceString(fk.ColumnsTo, from, to)
			}
		}
	}
}

// renameTableRefs points every foreign key that referenced the old
// table name at the new one, the way PostgreSQL does when it renames
// the relation out from under them.
func renameTableRefs(s *Snapshot, from, to string) {
	for _, t := range s.Tables {
		for _, fk := range t.ForeignKeys {
			if fk.TableFrom == from {
				fk.TableFrom = to
			}
			if fk.TableTo == from {
				fk.TableTo = to
			}
		}
	}
}

func replaceString(list []string, from, to string) {
	for i, v := range list {
		if v == from {
			list[i] = to
		}
	}
}

// splitTableRef resolves the name a Rename gives a table into the
// "schema.table" key a snapshot uses. A bare name means the public
// schema, which is the same default tableKey applies to a Table that
// never named one.
func splitTableRef(ref string) (key, schema, table string) {
	if i := strings.IndexByte(ref, '.'); i > 0 {
		return ref, ref[:i], ref[i+1:]
	}
	return "public." + ref, "public", ref
}

// qualifyLike puts ref in schema unless it already names one of its
// own. A table rename cannot move a table between schemas — PostgreSQL
// has ALTER TABLE ... SET SCHEMA for that — so the target inherits the
// source's schema rather than silently defaulting to public.
func qualifyLike(ref, schema string) string {
	if strings.IndexByte(ref, '.') > 0 {
		return ref
	}
	return schema + "." + ref
}

// cloneSnapshotTables copies a snapshot down to every field a rename
// rewrites, so the caller's snapshot keeps the shape it was read with.
// Enums, sequences and views are shared: no rename touches them.
func cloneSnapshotTables(s *Snapshot) *Snapshot {
	out := *s
	out.Tables = make(map[string]*TableSnapshot, len(s.Tables))
	for key, t := range s.Tables {
		out.Tables[key] = cloneTableSnapshot(t)
	}
	return &out
}

func cloneTableSnapshot(t *TableSnapshot) *TableSnapshot {
	out := *t
	out.Columns = make(map[string]*ColumnSnapshot, len(t.Columns))
	for k, v := range t.Columns {
		c := *v
		out.Columns[k] = &c
	}
	out.Indexes = make(map[string]*IndexSnapshot, len(t.Indexes))
	for k, v := range t.Indexes {
		i := *v
		i.Columns = append([]string(nil), v.Columns...)
		i.Include = append([]string(nil), v.Include...)
		out.Indexes[k] = &i
	}
	out.ForeignKeys = make(map[string]*ForeignKeySnapshot, len(t.ForeignKeys))
	for k, v := range t.ForeignKeys {
		f := *v
		f.ColumnsFrom = append([]string(nil), v.ColumnsFrom...)
		f.ColumnsTo = append([]string(nil), v.ColumnsTo...)
		out.ForeignKeys[k] = &f
	}
	out.UniqueConstraints = make(map[string]*UniqueSnapshot, len(t.UniqueConstraints))
	for k, v := range t.UniqueConstraints {
		u := *v
		u.Columns = append([]string(nil), v.Columns...)
		out.UniqueConstraints[k] = &u
	}
	out.CompositePrimaryKeys = make(map[string]*CompositePKSnapshot, len(t.CompositePrimaryKeys))
	for k, v := range t.CompositePrimaryKeys {
		p := *v
		p.Columns = append([]string(nil), v.Columns...)
		out.CompositePrimaryKeys[k] = &p
	}
	out.CheckConstraints = make(map[string]*CheckSnapshot, len(t.CheckConstraints))
	for k, v := range t.CheckConstraints {
		c := *v
		out.CheckConstraints[k] = &c
	}
	out.Policies = make(map[string]*PolicySnapshot, len(t.Policies))
	for k, v := range t.Policies {
		out.Policies[k] = v
	}
	return &out
}
