// Code generated by dropsgen. DO NOT EDIT.

package models

import "github.com/bernardoforcillo/drops"

// User bindings ----------------------------------------------------

// ColsUser returns the column names in the order
// BindUser / ScanUser use.
func ColsUser() []string {
	return []string{
		"id",
		"name",
		"email",
	}
}

// BindUser returns r's field values in column order,
// ready to pass to a parameterised INSERT or UPDATE.
func BindUser(r *User) []any {
	return []any{
		r.ID,
		r.Name,
		r.Email,
	}
}

// ScanUser scans one row from rows into dest. The row's
// column order must match ColsUser(); use a SELECT that
// lists the columns explicitly via ColsUser() to keep
// them aligned.
func ScanUser(rows drops.Rows, dest *User) error {
	return rows.Scan(
		&dest.ID,
		&dest.Name,
		&dest.Email,
	)
}

// Post bindings ----------------------------------------------------

// ColsPost returns the column names in the order
// BindPost / ScanPost use.
func ColsPost() []string {
	return []string{
		"id",
		"user_id",
		"title",
	}
}

// BindPost returns r's field values in column order,
// ready to pass to a parameterised INSERT or UPDATE.
func BindPost(r *Post) []any {
	return []any{
		r.ID,
		r.UserID,
		r.Title,
	}
}

// ScanPost scans one row from rows into dest. The row's
// column order must match ColsPost(); use a SELECT that
// lists the columns explicitly via ColsPost() to keep
// them aligned.
func ScanPost(rows drops.Rows, dest *Post) error {
	return rows.Scan(
		&dest.ID,
		&dest.UserID,
		&dest.Title,
	)
}
