// Code generated by dropsgen. DO NOT EDIT.

package models

import "github.com/bernardoforcillo/drops/pg"

// User bindings ----------------------------------------------------

// ColsUser returns the column names in the order
// BindUser / ScanUser use.
func ColsUser() []string {
	return []string{
		"id",
		"name",
		"email",
	}
}

// BindUser returns r's field values in column order,
// ready to pass to a parameterised INSERT or UPDATE.
func BindUser(r *User) []any {
	return []any{
		r.ID,
		r.Name,
		r.Email,
	}
}

// ScanUser scans one row into dest by position. The row's
// column order must match ColsUser(); RegisterUser
// hands both to the entity together, so every fast-path SELECT it
// issues lists these columns in this order. A hand-written SELECT
// feeding this function has to do the same.
func ScanUser(rows pg.Scanner, dest *User) error {
	return rows.Scan(
		&dest.ID,
		&dest.Name,
		&dest.Email,
	)
}

// RegisterUser wires the zero-reflection scanner and the
// column list it was generated for into e, so Entity.Get /
// EntityQuery.All / EntityQuery.One take the fastpath and render
// ColsUser() instead of "*". Panics if the schema no
// longer has one of those columns — re-run go generate. Call once at
// init():
//
//	func init() { RegisterUser(UsersEntity) }
func RegisterUser(e *pg.Entity[User]) *pg.Entity[User] {
	return e.SetFastScan(ColsUser(), ScanUser)
}

// Post bindings ----------------------------------------------------

// ColsPost returns the column names in the order
// BindPost / ScanPost use.
func ColsPost() []string {
	return []string{
		"id",
		"user_id",
		"title",
	}
}

// BindPost returns r's field values in column order,
// ready to pass to a parameterised INSERT or UPDATE.
func BindPost(r *Post) []any {
	return []any{
		r.ID,
		r.UserID,
		r.Title,
	}
}

// ScanPost scans one row into dest by position. The row's
// column order must match ColsPost(); RegisterPost
// hands both to the entity together, so every fast-path SELECT it
// issues lists these columns in this order. A hand-written SELECT
// feeding this function has to do the same.
func ScanPost(rows pg.Scanner, dest *Post) error {
	return rows.Scan(
		&dest.ID,
		&dest.UserID,
		&dest.Title,
	)
}

// RegisterPost wires the zero-reflection scanner and the
// column list it was generated for into e, so Entity.Get /
// EntityQuery.All / EntityQuery.One take the fastpath and render
// ColsPost() instead of "*". Panics if the schema no
// longer has one of those columns — re-run go generate. Call once at
// init():
//
//	func init() { RegisterPost(PostsEntity) }
func RegisterPost(e *pg.Entity[Post]) *pg.Entity[Post] {
	return e.SetFastScan(ColsPost(), ScanPost)
}
