// Code generated by dropsgen. DO NOT EDIT.

package models

import "github.com/bernardoforcillo/drops/pg"

// User bindings ----------------------------------------------------

// ColsUser returns the column names in the order
// BindUser / ScanUser use.
func ColsUser() []string {
	return []string{
		"id",
		"name",
		"email",
	}
}

// BindUser returns r's field values in column order,
// ready to pass to a parameterised INSERT or UPDATE.
func BindUser(r *User) []any {
	return []any{
		r.ID,
		r.Name,
		r.Email,
	}
}

// ScanUser scans one row into dest. The row's column
// order must match ColsUser(); use a SELECT that lists
// the columns explicitly via ColsUser() to keep them
// aligned.
func ScanUser(rows pg.Scanner, dest *User) error {
	return rows.Scan(
		&dest.ID,
		&dest.Name,
		&dest.Email,
	)
}

// RegisterUser wires the zero-reflection scanner into e
// so Entity.Get / EntityQuery.All / EntityQuery.One take the
// fastpath. Call once at init():
//
//	func init() { RegisterUser(UsersEntity) }
func RegisterUser(e *pg.Entity[User]) *pg.Entity[User] {
	return e.SetFastScan(ScanUser)
}

// Post bindings ----------------------------------------------------

// ColsPost returns the column names in the order
// BindPost / ScanPost use.
func ColsPost() []string {
	return []string{
		"id",
		"user_id",
		"title",
	}
}

// BindPost returns r's field values in column order,
// ready to pass to a parameterised INSERT or UPDATE.
func BindPost(r *Post) []any {
	return []any{
		r.ID,
		r.UserID,
		r.Title,
	}
}

// ScanPost scans one row into dest. The row's column
// order must match ColsPost(); use a SELECT that lists
// the columns explicitly via ColsPost() to keep them
// aligned.
func ScanPost(rows pg.Scanner, dest *Post) error {
	return rows.Scan(
		&dest.ID,
		&dest.UserID,
		&dest.Title,
	)
}

// RegisterPost wires the zero-reflection scanner into e
// so Entity.Get / EntityQuery.All / EntityQuery.One take the
// fastpath. Call once at init():
//
//	func init() { RegisterPost(PostsEntity) }
func RegisterPost(e *pg.Entity[Post]) *pg.Entity[Post] {
	return e.SetFastScan(ScanPost)
}
