package integration_test

import (
	"context"
	"encoding/json"
	"testing"
	"time"

	"github.com/bernardoforcillo/drops/sqlite"
)

// The transactional outbox is the mechanism drops/mirror depends on for
// its delivery guarantee, and it had never been run against a database.
func TestOutboxAgainstTheEngine(t *testing.T) {
	db := openSQLite(t)
	ctx := context.Background()

	obTable := sqlite.NewOutboxTable("outbox")
	exec(t, db, sqlite.CreateTable(obTable))
	ob := sqlite.NewOutbox(db, "outbox")

	// The point of an outbox: the event and the mutation share a fate.
	if err := db.InTx(ctx, func(tx *sqlite.DB) error {
		return ob.Emit(tx, ctx, "user.created", map[string]any{"id": 1})
	}); err != nil {
		t.Fatalf("emit in tx: %v", err)
	}

	events, err := ob.Drain(ctx, 10)
	if err != nil {
		t.Fatalf("Drain: %v", err)
	}
	if len(events) != 1 {
		t.Fatalf("drained %d events, want 1", len(events))
	}
	if events[0].Kind != "user.created" {
		t.Errorf("kind = %q", events[0].Kind)
	}
	var payload map[string]any
	if err := json.Unmarshal(events[0].Payload, &payload); err != nil {
		t.Fatalf("payload did not survive the round trip: %v (%s)", err, events[0].Payload)
	}
	if payload["id"] != float64(1) {
		t.Errorf("payload = %v", payload)
	}

	// A rolled-back transaction must leave nothing behind.
	_ = db.InTx(ctx, func(tx *sqlite.DB) error {
		if err := ob.Emit(tx, ctx, "user.deleted", map[string]any{"id": 2}); err != nil {
			return err
		}
		return errRollback
	})
	after, err := ob.Drain(ctx, 10)
	if err != nil {
		t.Fatal(err)
	}
	for _, e := range after {
		if e.Kind == "user.deleted" {
			t.Fatal("an event survived a rolled-back transaction; the outbox guarantee does not hold")
		}
	}

	// Acknowledging removes it from the drain set, or a worker loops
	// on the same event forever.
	if err := ob.MarkPublished(ctx, events[0].ID); err != nil {
		t.Fatalf("MarkPublished: %v", err)
	}
	remaining, err := ob.Drain(ctx, 10)
	if err != nil {
		t.Fatal(err)
	}
	for _, e := range remaining {
		if e.ID == events[0].ID {
			t.Error("a published event was drained again")
		}
	}
}

var errRollback = &rollbackErr{}

type rollbackErr struct{}

func (*rollbackErr) Error() string { return "deliberate rollback" }

// Migrations: up, status, and down. Statements generated by drops and
// applied by the engine, with the version table drops manages.
func TestMigrationsAgainstTheEngine(t *testing.T) {
	db := openSQLite(t)
	ctx := context.Background()

	m := sqlite.NewMigrator(db).
		AddSQL("0001", "create_widgets",
			`CREATE TABLE "widgets" ("id" INTEGER PRIMARY KEY, "name" TEXT NOT NULL)`,
			`DROP TABLE "widgets"`).
		AddSQL("0002", "add_colour",
			`ALTER TABLE "widgets" ADD COLUMN "colour" TEXT`,
			`ALTER TABLE "widgets" DROP COLUMN "colour"`)

	if err := m.Up(ctx); err != nil {
		t.Fatalf("Up: %v", err)
	}
	if _, err := db.Exec(ctx, `INSERT INTO "widgets" ("name","colour") VALUES ('a','red')`); err != nil {
		t.Fatalf("the migrated schema is not what it claims: %v", err)
	}

	status, err := m.Status(ctx)
	if err != nil {
		t.Fatalf("Status: %v", err)
	}
	if len(status) != 2 {
		t.Fatalf("status reports %d migrations, want 2", len(status))
	}
	for _, s := range status {
		if !s.Applied {
			t.Errorf("migration %s reports unapplied after Up", s.Version)
		}
	}

	// Up must be idempotent — a redeploy runs it again.
	if err := m.Up(ctx); err != nil {
		t.Fatalf("second Up: %v", err)
	}

	if err := m.Down(ctx); err != nil {
		t.Fatalf("Down: %v", err)
	}
	if _, err := db.Exec(ctx, `INSERT INTO "widgets" ("name","colour") VALUES ('b','blue')`); err == nil {
		t.Error("Down reported success but the column is still there")
	}
}

// Soft delete rewrites DELETE into UPDATE and hides the row from every
// subsequent query. Both halves need a server to be believed.
func TestSoftDeleteAgainstTheEngine(t *testing.T) {
	db := openSQLite(t)
	ctx := context.Background()

	tbl := sqlite.NewTable("posts")
	sqlite.Add(tbl, sqlite.BigInt("id").PrimaryKey().AutoIncrement())
	title := sqlite.Add(tbl, sqlite.Text("title").NotNull())
	sd := sqlite.SoftDelete(tbl)
	tbl.DefaultFilter(sd.DeletedAt.IsNull())
	exec(t, db, sqlite.CreateTable(tbl))

	type post struct {
		ID    int64
		Title string
	}
	ent := sqlite.NewEntity[post](tbl)

	p := post{Title: "hello"}
	if err := ent.Create(db, ctx, &p); err != nil {
		t.Fatalf("Create: %v", err)
	}
	if p.ID == 0 {
		t.Fatal("no key came back")
	}

	if _, err := ent.SoftDeleteByID(db, ctx, p.ID, sd); err != nil {
		t.Fatalf("SoftDeleteByID: %v", err)
	}

	live, err := ent.Query(db).All(ctx)
	if err != nil {
		t.Fatal(err)
	}
	if len(live) != 0 {
		t.Errorf("a soft-deleted row is still visible: %+v", live)
	}

	all, err := ent.Query(db).Unscoped().All(ctx)
	if err != nil {
		t.Fatal(err)
	}
	if len(all) != 1 {
		t.Errorf("Unscoped should see the hidden row, got %d", len(all))
	}

	if _, err := ent.Restore(db, ctx, p.ID, sd); err != nil {
		t.Fatalf("Restore: %v", err)
	}
	back, err := ent.Query(db).All(ctx)
	if err != nil {
		t.Fatal(err)
	}
	if len(back) != 1 || back[0].Title != "hello" {
		t.Errorf("Restore did not bring the row back: %+v", back)
	}
	_ = title
	_ = time.Now
}
